# Generated by Django 4.0.3 on 2022-03-25 15:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_information_date_debts'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_balance', models.FloatField(default=0)),
                ('new_balance', models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Name',
        ),
    ]
