# Generated by Django 4.0.3 on 2022-03-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_history_delete_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='select',
            field=models.CharField(default='Add Debts', max_length=15),
        ),
    ]
