# Generated by Django 4.0.3 on 2022-04-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_bitcoin_history_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
