# Generated by Django 4.0.3 on 2022-04-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_information_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='amount',
        ),
        migrations.AddField(
            model_name='bitcoin',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
