# Generated by Django 4.0.3 on 2022-04-02 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_information_amount_bitcoin_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitcoin',
            name='amount',
        ),
    ]
