# Generated by Django 4.0.3 on 2022-04-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_bitcoin_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitcoin',
            name='current_price',
        ),
        migrations.AddField(
            model_name='bitcoin',
            name='rank',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bitcoin',
            name='status',
            field=models.CharField(default='Increase', max_length=25),
        ),
    ]
