# Generated by Django 4.0.3 on 2022-04-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_bitcoin_current_price_bitcoin_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitcoin',
            name='url',
            field=models.CharField(default='https://www.coingecko.com/en/coins/plant-vs-undead-token/php', max_length=500),
        ),
    ]
