# Generated by Django 4.0.3 on 2022-04-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_bitcoin_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitcoin',
            name='current',
            field=models.FloatField(default=0),
        ),
    ]
